language: python
sudo: required
services:
- docker
python:
- '3.5'
- '3.6'
install:
- pip install mypy
- pip install coveralls
- pip install pycodestyle
- pip install --upgrade .
script:
- mypy --ignore-missing-imports houston
- pycodestyle houston
- pytest test
- coverage run --source=houston setup.py test
after_success:
  - coveralls
notifications:
  email: false
