language: python
sudo: required
services:
- docker
python:
- '3.5'
- '3.6'
install:
- pip install pycodestyle
- pip install --upgrade .
script:
- pycodestyle houston
- pytest test
notifications:
  email: false
